#ENC[AES256_GCM,data:sV46cVBeBK7+YzMiRjpD4Yriemv1AvHMtwA=,iv:LiRMBhMZzoiNh6Oj74H2psmkDH39gbL9kdYpl+hol5g=,tag:zg2z62vZmMPbEKay3iFyBg==,type:comment]
DATABASE_URL: ENC[AES256_GCM,data:N8lP40RsBfS67E8rDCZAb0dhJhIHQAiydX7HqSoVpF5wVSqurvairpb1SXoGxq/gaEHn4fbWU2WBBgdKcpS+ffjrX6Migg==,iv:cZs9jteUU5uvws5wy+OtFf88NVUu2xfZc38o522qcM0=,tag:aOHS60yHPlXh1SFM3Y1aug==,type:str]
JWT_SECRET: ENC[AES256_GCM,data:FULlqdhpDO6jJa6dYBAuhv99SCSC3XuSL0mCVL74j1hkCn6S,iv:Iym5Ue90yxcwFpCv/BA+LGSSluCAJYlYEp3r3ZOLb6w=,tag:1GfDicEiGTA15//3kXz6aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzh7ep5wt8e9qchsefafy64f7a9fufudvmw5uau92yf0hm3gtqfq4xmc4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V0N2eXdQL0U4dE80WS9R
            M2ZmL1FxcmU0Nld5OUtpSExTelJtSHpkSVhrCjVwTlVvRFk3eTVFOXlWdU10Zmkw
            SHUyTW12RGhoVktXWEJJTDhBTFNHTU0KLS0tIDRyOVRteVduWlNmNk9FZFBBeTds
            ZVB5Z2tCZ1NnaGVZcDVKWkFKN2k3TGsKcLmLw982baYWPeRRu4amlOlghtL3Ssn3
            xwnrP/34eF8l4W6W1yFwPU++33RkQjrOaXrlB3SF9FtDPO5/r/H2YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T09:25:36Z"
    mac: ENC[AES256_GCM,data:K6TdoPL8C8RjNOs5aScLU1sGBTXXOoOaDq8foq+7DwRxPjk/sceZKgf/kEMYAV8JV72/yv69M51AG9ubIR/A4khl7xNj+JGaMO7jkge8uAxPHDKppSV68LjlSkifd1/tpyMBnNukc44uWPfy85LF5FstLE7tL/3TMwDLNb/J2lg=,iv:orNASL7745qUnVV/3cI4GUYKzfdl8mDGH7TprLGq8h4=,tag:mioBGlheu/Kx3JDAZkVpOQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
